colors: 
    extension: -colors.json
    output: .config/powerline
colorschemes_base16:
    extension: .json
    output: .config/powerline/colorschemes
colorschemes_base16:
    extension: .json
    output: .config/powerline/colorschemes/shell
colorschemes_vim_base16:
    extension: .json
    output: .config/powerline/colorschemes/vim
