colors: 
    filename: colors.json
    output: .config/powerline
colorschemes-base16:
    extension: .json
    output: .config/powerline/colorschemes
colorschemes-base16:
    extension: .json
    output: .config/powerline/colorschemes/shell
colorschemes-vim-base16:
    extension: .json
    output: .config/powerline/colorschemes/vim
